### ISSUE TITLE
Connection Reset on VanillaGradle 0.2

### ISSUE THREAD

**Issue by nightlyDuck** [SpongePowered/VanillaGradle#107]
Trying use VanillaGradle with minecraft server version 1.19.4, got error - https://pastes.dev/dSYex5zilP
settings.gradle file - https://pastes.dev/ICnmhCwZ3Z
Gradle version - 8.1.1
![image](https://github.com/SpongePowered/VanillaGradle/assets/102286502/8d8b10bc-6a01-433c-b36f-94c82a465913)

**Comment by zml2008** [comment]
0.2.1-SNAPSHOT
