### ISSUE TITLE
Vineflower change has vanilla gradle unable to apply plugin class 'org.spongepowered.gradle.vanilla.internal.ProvideMinecraftPlugin'

### ISSUE THREAD

**Issue by ExcessiveAmountsOfZombies** [SpongePowered/VanillaGradle#111]
repo: https://github.com/ExcessiveAmountsOfZombies/jEEPersShops

This happens on line 2 in the root build.gradle

Stacktrace:
https://gist.github.com/ExcessiveAmountsOfZombies/94634aa015b6a1755206c28b6f469192

**Comment by zml2008** [comment]
Update gradle

**Comment by MentalIllness** [comment]
Shouldn't close the issue before a feedback. Anyways I have the same issue, tried like 5 different Gradle versions, but it's still happening.
