### ISSUE TITLE
org.spongepowered.gradle.vanilla.internal.ProvideMinecraftPlugin

### ISSUE THREAD

**Issue by ebullienc3** [SpongePowered/VanillaGradle#112]
I have this problem when I try to build Croptopia ( https://github.com/ExcessiveAmountsOfZombies/jEEPersShops )
The same error as showed here: https://gist.github.com/ExcessiveAmountsOfZombies/94634aa015b6a1755206c28b6f469192

**Comment by zml2008** [comment]
Duplicate of #111

**Comment by rockfordroeNG** [comment]
I'm still having this issue after upgrading to Gradle 8.2.1 for FerriteCore

https://pastebin.com/XcZjaJkz
