### ISSUE TITLE
Investigate tasks not caching correctly.

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/VanillaGradle#12]

**Comment by zml2008** [comment]
Looked into Gradle's logs. What seems to be happening is, any time the build classpath changes in a way that afferts VanillaGradle, the whole cache is invalidated. I think that's a reasonable choice for now, given how fast regeneration is. As VanillaGradle becomes more stable, we can look into adopting our own method for up-to-date checks, but for now using Gradle's choices is safer.
