### ISSUE TITLE
Could not resolve net.minecraft:joined:1.20.1

### ISSUE THREAD

**Issue by huskcasaca** [SpongePowered/VanillaGradle#151]
I'm getting this error message from gradle since last week. It's currently affecting all versions. May I ask if there any changes in sponge maven repo?

`sponge-test:main: Could not resolve net.minecraft:joined:1.20.1.`

Gradle: 8.5, Java: 18.0.2, JVM: 18.0.2+9-61 (Oracle Corporation), Arch: aarch64

build.gradle

```
plugins {
    id 'java'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}

repositories {
    mavenCentral()
}

minecraft {
    version '1.20.1'
}
````

settings.gradle

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri('https://repo.spongepowered.org/repository/maven-public/')
        }
    }
}
```

**Comment by zml2008** [comment]
update gradle
