### ISSUE TITLE
[Feature] Option to allow minecraft and deps to be shadowed

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [SpongePowered/VanillaGradle#163]
I have a use case where I want to shadow including deps and minecraft for some runtime classloading.
A simple config option in the gradle.build or gradle properties is fine.

Thanks!

**Comment by zml2008** [comment]
no

**Comment by KrystilizeNevaDies** [comment]
Okay, could I be offered an explanation at least?
Is it due to concerns around distribution?

**Comment by zml2008** [comment]
it's not a goal of the project
