### ISSUE TITLE
Unresolved reference: grgit

### ISSUE THREAD

**Issue by alexandrage** [SpongePowered/VanillaGradle#20]
> Configure project :
e: C:\Users\alexa\Desktop\VanillaGradle-master\VanillaGradle-master\build.gradle.kts:83:41: Unresolved reference: grgit
e: C:\Users\alexa\Desktop\VanillaGradle-master\VanillaGradle-master\build.gradle.kts:84:41: Unresolved reference: grgit

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\alexa\Desktop\VanillaGradle-master\VanillaGradle-master\build.gradle.kts' line: 83

* What went wrong:
Script compilation errors:

  Line 83:     manifest.attributes["Git-Commit"] = grgit.head().id
                                                   ^ Unresolved reference: grgit

  Line 84:     manifest.attributes["Git-Branch"] = grgit.branch.current().name
                                                   ^ Unresolved reference: grgit

2 errors

**Comment by zml2008** [comment]
We only support compiling from a git checkout, not a zip download
