### ISSUE TITLE
Where is "0.2.1-SNAPSHOT"?

### ISSUE THREAD

**Issue by ypo-GitHub** [SpongePowered/VanillaGradle#77]
there are my mavens:
maven(https://maven.minecraftforge.net)
    maven2(https://files.minecraftforge.net/maven/)
    maven3(https://repo.spongepowered.org/repository/maven-public/)
    maven4(https://repo.spongepowered.org/maven)
    maven5(https://maven.enaium.cn/)
    MavenRepo
    Gradle Central Plugin Repository

but Where is the "0.2.1-SNAPSHOT"?

**Comment by zml2008** [comment]
This is a bugtracker, not a support forum
